---
- name: Verify sshd_config and access
  ansible.builtin.import_tasks: sshd_config.yml
  tags: [sshd_config]

- name: Verify auth.log
  ansible.builtin.import_tasks: auth_log.yml
  tags: [auth_log]
