- name: Collect information about services
  ansible.builtin.service_facts:
  tags: [collect_info]

- name: Verify ssh service
  ansible.builtin.import_tasks: verify_ssh_service.yml
  tags: [ssh_service]
