---
- name: Collect information about services
  ansible.builtin.service_facts:
  tags: [always]

- name: Verify iptables / netfilter-persistent
  ansible.builtin.import_tasks: iptables.yml
  tags: [iptables]

- name: Verify Kaspersky services
  ansible.builtin.import_tasks: kaspersky.yml
  tags: [kaspersky]
