---
- name: Verify installed packages
  ansible.builtin.import_playbook: verify_packages.yml

- name: Verify SSH hardening
  ansible.builtin.import_playbook: verify_ssh_hardening.yml

- name: Verify password policy
  ansible.builtin.import_playbook: verify_password_policy.yml

- name: Verify fail2ban
  ansible.builtin.import_playbook: verify_fail2ban.yml

- name: Verify services
  ansible.builtin.import_playbook: verify_services.yml

- name: Verify glpi-agent
  ansible.builtin.import_playbook: verify_glpi_agent.yml

- name: Verify zabbix-agent
  ansible.builtin.import_playbook: verify_zabbix_agent.yml

- name: Verify wazuh-agent
  ansible.builtin.import_playbook: verify_wazuh_agent.yml

- name: Aggregate all reports per host
  ansible.builtin.import_playbook: aggregate_reports.yml
